module.exports = {
  apps: [
    {
      name: 'itzalan-api',
      cwd: 'C:\\Users\\ciade\\Downloads\\ITZALAN TECH – AUTOMATIZACIÓN LEGAL',
      script: 'node',
      args: 'apps/api/dist/main.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_restarts: 10,
      restart_delay: 2000,
      max_memory_restart: '512M',
      env_file: '.env.production',
      env: {
        NODE_ENV: 'production',
        PORT: 3001,
      },
      out_file: '/var/log/itzalan/api.out.log',
      error_file: '/var/log/itzalan/api.err.log',
      merge_logs: true,
      time: true,
    },
    {
      name: 'itzalan-web',
      cwd: 'C:\\Users\\ciade\\Downloads\\ITZALAN TECH – AUTOMATIZACIÓN LEGAL',
      script: 'npm',
      args: '--workspace @itzalan/web run start -- -p 3000 -H 0.0.0.0',
      instances: 1,
      autorestart: true,
      watch: false,
      max_restarts: 10,
      restart_delay: 2000,
      max_memory_restart: '512M',
      env_file: '.env.production',
      env: {
        NODE_ENV: 'production',
      },
      out_file: '/var/log/itzalan/web.out.log',
      error_file: '/var/log/itzalan/web.err.log',
      merge_logs: true,
      time: true,
    },
  ],
};
